### ISSUE TITLE
Cad isnt working

### ISSUE THREAD

**Issue by Luzox** [michael86/esx_cad#2]
Hi,

CAD isnt working submit isnt working.
Cant find people with the right information and cant add reports. (The bootstrap tables are to wide.)

I know its a work in progress great work so far!

[![image](https://user-images.githubusercontent.com/2470059/63635790-18b5a780-c667-11e9-9a91-69b2e109796a.png)](url)

**Comment by Luzox** [comment]
fixed it.

**Comment by michael86** [comment]
What part of submit is not working? Also what resolution you using?

**Comment by michael86** [comment]
Just uplaoded a new css file. Can you try that please and let me know if the forms aren't breaking out of the image. Don't worry about the height for the time being, i know about that and will fix if the new style.css fixes the width issue.

**Comment by Luzox** [comment]
Ok, i cant submit a report. submit button isnt doing anything.  ill check the new css file.

Maybe an idea for the table is to fixed position for the top line (names of the tables)

**Comment by michael86** [comment]
Any errors printing out to server or f8 console when you try and submit a report? Like I've said to others, there are other people that are using this and it's working fine.

**Comment by Luzox** [comment]
The forms / tables are to low , width is working.

[https://i.ibb.co/XyTzCm7/error.png](url)

**Comment by michael86** [comment]
yeah the tables being low is fine, I just wanted to test the width for now. I'll bring the tables up a bit when I'm back home. As for the error, by any chance are you trying to submit a report without a name?

**Comment by Luzox** [comment]
i have information in de field, i get result no one found.

**Comment by michael86** [comment]
Okay, so from what I can see in the error, it's either failing to get the identifer from the users table or it's failing to capitlise the the name correctly. In your users database, are the rp names capitlised correctly? 

I.E: First Last

or are they lowercase:

first last

**Comment by Luzox** [comment]
Tried, i think it has to do with the day of birth in the database it is like 1990-12-02 (So year month day) your cad is with / instead of - maybe that is the problem?

**Comment by michael86** [comment]
Yeah, 100% that would cause a problem. My server only accepts dd/mm/yyyy as the dob input. The problem is, if people are using esx_identity. Certain versions use a standard input field which allows mm-dd-yyyy or dd-mm-yyyy or in your case yyyy-mm-dd. There's no real formatting to it! Which results in the problem you're having. Unfortunately, I can't just use the identifiers, as there's the possibility that two players have the same name. Hence the need to use a dob as well to get the exact profile along with the correct identifier.

**Comment by Luzox** [comment]
ill edit my registration to format then it should work 👍   ill try it and i will let you know

**Comment by Luzox** [comment]
[https://i.ibb.co/bvgVS4n/cadnotworking.png](url)

Still isnt working.

**Comment by michael86** [comment]
hmmm.... Interesting, that should be finding it! Is it still giving you the same error?

**Comment by michael86** [comment]
Just commited a new style.css that should sort out the rest of the 1920x1080 alignment. If you could test it and let me know if it works for you. Also if anything appears out of line, could you let me know as well please.

**Comment by Luzox** [comment]
Ok, and yes same error cant find any persons from the db.

**Comment by Luzox** [comment]
Found it, its working my db date wasnt corrent Month & day wrong way..

**Comment by michael86** [comment]
aaa yeah, dd/mm/yyyy. Another collaberator has made a second sql query to check for mm/dd/yyyy, just waiting on him to send it over.
