### ISSUE TITLE
buying vehicles isnt saving in database

### ISSUE THREAD

**Issue by wrathster2103** [michael86/esx_cad#3]
im getting this error when I purchase a vehicle

[ERROR] [MySQL] An error happens on MySQL for query "INSERT INTO owned_vehicles (owner, plate, vehicle, ownerName) VALUES (@owner, @plate, @vehicle, @ownerName) {@vehicle={"modRearBumper":-1,"modRoof":-1,"modBrakes":-1,"modArmor":-1,"modFrontBumper":-1,"modExhaust":-1,"modAPlate":-1,"modAerials":-1,"modWindows":-1,"pearlescentColor":111,"modFrontWheels":-1,"modTrunk":-1,"modVanityPlate":-1,"modXenon":false,"modSmokeEnabled":false,"modBackWheels":-1,"modOrnaments":-1,"modStruts":-1,"wheels":0,"modPlateHolder":-1,"health":1000,"modShifterLeavers":-1,"modHood":-1,"modFrame":-1,"modGrille":-1,"modDashboard":-1,"modEngine":-1,"modSteeringWheel":-1,"modSpoilers":-1,"wheelColor":156,"modDial":-1,"modTransmission":-1,"modDoorSpeaker":-1,"tyreSmokeColor":[255,255,255],"modTank":-1,"modAirFilter":-1,"modSideSkirt":-1,"model":-344943009,"modArchCover":-1,"dirtLevel":11.000003814698,"modTurbo":false,"color1":6,"modHydrolic":-1,"neonEnabled":[false,false,false,false],"modEngineBlock":-1,"modTrimA":-1,"modTrimB":-1,"neonColor":[255,0,255],"modSeats":-1,"windowTint":-1,"modSuspension":-1,"modLivery":-1,"color2":0,"plate":"FXU 360","modHorns":-1,"modSpeakers":-1,"plateIndex":0,"modRightFender":-1,"modFender":-1};@plate=FXU 360;@owner=steam:110000132fe65d6}": Column 'ownerName' cannot be null

**Comment by michael86** [comment]
Did you add the function to the bottom that grabs the rp name?

**Comment by wrathster2103** [comment]
yeah this is the bottom of my server/server.lua from vehicleshop


			TriggerEvent('esx_addonaccount:getSharedAccount', 'society_cardealer', function(account)
				account.addMoney(result[i].rent_price)
			end)
		end
	end)
end

TriggerEvent('cron:runAt', 22, 00, PayRent)

--crumblecad

function GetCharacterName(source)
    local result =
    MySQL.Sync.fetchAll(
    'SELECT firstname, lastname FROM users WHERE identifier = @identifier',
    {
        ['@identifier'] = GetPlayerIdentifiers(source)[1]
    })
    
    if result[1] and result[1].firstname and result[1].lastname then
        return ('%s %s'):format(result[1].firstname, result[1].lastname)
    end
end

**Comment by michael86** [comment]
Can you post your sql query as well please.

**Comment by wrathster2103** [comment]
SELECT * FROM `owned_vehicles` WHERE 1

**Comment by michael86** [comment]
Wrong query, the one you posted above with the ownerName added to it.

**Comment by wrathster2103** [comment]
egisterServerEvent('esx_vehicleshop:setVehicleOwned')
AddEventHandler('esx_vehicleshop:setVehicleOwned', function (vehicleProps)
	local _source = source
	local xPlayer = ESX.GetPlayerFromId(_source)

	MySQL.Async.execute('INSERT INTO owned_vehicles (owner, plate, vehicle, ownerName) VALUES (@owner, @plate, @vehicle, @ownerName)',
	{
		['@owner']   = xPlayer.identifier,
		['@plate']   = vehicleProps.plate,
		['@vehicle'] = json.encode(vehicleProps),
	    ['@ownerName'] = name
	}, function (rowsChanged)
		TriggerClientEvent('esx:showNotification', _source, _U('vehicle_belongs', vehicleProps.plate))
	end)
end)

**Comment by michael86** [comment]
underneath the 
```
local xPlayer = ESX.GetPlayerFromId(_source)
```

add

```
local name = GetCharacterName(source)
```

so the whole thing should look like

```lua
RegisterServerEvent('esx_vehicleshop:setVehicleOwned')
AddEventHandler('esx_vehicleshop:setVehicleOwned', function (vehicleProps)
local _source = source
local xPlayer = ESX.GetPlayerFromId(_source)
local name = GetCharacterName(source)

MySQL.Async.execute('INSERT INTO owned_vehicles (owner, plate, vehicle, ownerName) VALUES (@owner, @plate, @vehicle, @ownerName)',
{
	['@owner']   = xPlayer.identifier,
	['@plate']   = vehicleProps.plate,
	['@vehicle'] = json.encode(vehicleProps),
    ['@ownerName'] = name
}, function (rowsChanged)
	TriggerClientEvent('esx:showNotification', _source, _U('vehicle_belongs', vehicleProps.plate))
end)
end)```

**Comment by wrathster2103** [comment]
doh, thank you will put that in and try

**Comment by michael86** [comment]
no worries

**Comment by wrathster2103** [comment]
ok 2 questions, what about all the cars previous? and is it possible to search without D.OB? cos some players have done theirs yyyy/mm/dd

**Comment by wrathster2103** [comment]
but it worked I bought a car and it saved it

**Comment by wrathster2103** [comment]
cant search vehicle on cad though

**Comment by michael86** [comment]
DOB no, it has to be included, if you have a player that has the same name as someone else, it would return both profiles and would cause problems. I may change it in a future update 🤷‍♂ I can upload my version of esx_identity if you want, that's edited to only accept dd/mm/yyyy.

I've just discovered vehicle search is broken again, looking into it now.

**Comment by wrathster2103** [comment]
your version is defo different to mine, cos that first part where to add the trigger, mine didnt look like yours

**Comment by wrathster2103** [comment]
but i can manually change their date of birth anyway,

**Comment by wrathster2103** [comment]
so all previous vehicles wont show up in cad?

**Comment by wrathster2103** [comment]
also is it set to police only?

**Comment by michael86** [comment]
No, not unless you create a sql query to update the column. You could probably pull all identifiers and plates from owned_vehicles. Then pull firstname, lastname from users where identifier = identifier and lastly, set ownerName to firstname & last name where plate = plate 

Bearin mind, this is still a work in progress, so there's going to be issues.

**Comment by michael86** [comment]
yeah police, and you have to move 5.0 radious from your spawn point when you first log in before oyu can open it, as esx_identity would throw errors when registering users.

**Comment by wrathster2103** [comment]
yeah thats cool i understand, just wondered how you would grab previous vehicles, im no good with all this code stuff,

**Comment by michael86** [comment]
Just pushed an update to fix the vehicle search issue. It should now work

**Comment by wrathster2103** [comment]
ok thanks, do i just need to restart for it to take place?

**Comment by michael86** [comment]
you could probably restart the script but always better to restart server
