### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by ShiftyOG** [michael86/esx_cad#4]
Can you optimize the script for 4k users?

Also im using esx_Kashacters. Can you make a fix for when an user makes a second character? The scripts outputs an error since the identifier is in use. So it does not save the enw character in cad_users

**Comment by michael86** [comment]
This is not a cad problem... You need to add the cad tables to the
server.lua in esx_kashacters like the kashacters readme states.

**Comment by michael86** [comment]
https://forum.fivem.net/t/release-esx-kashacters-multi-character/251613

local identifiersTables
